---
- name: validate nginx config
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0
  listen: reload nginx
  become: true

- name: reload nginx
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    state: reloaded
  listen: reload nginx
  become: true
