import { PERMISSIONS } from "./permissions";

export const USER_PERMISSIONS = [
    PERMISSIONS.USER.READ_OWN_PROFILE,
    PERMISSIONS.USER.UPDATE_OWN_PROFILE,

    PERMISSIONS.COMMON.READ_LANGUAGE,
];

export const ADMIN_PERMISSIONS = [
    PERMISSIONS.ADMIN.ADMINISTRATION_ACCESS,
    // permissions management
    PERMISSIONS.ADMIN.CREATE_PERMISSION,
    PERMISSIONS.ADMIN.READ_PERMISSION,
    PERMISSIONS.ADMIN.UPDATE_PERMISSION,
    PERMISSIONS.ADMIN.DELETE_PERMISSION,
    // role management
    PERMISSIONS.ADMIN.CREATE_ROLE,
    PERMISSIONS.ADMIN.READ_ROLE,
    PERMISSIONS.ADMIN.UPDATE_ROLE,
    PERMISSIONS.ADMIN.DELETE_ROLE,
    // user management
    PERMISSIONS.ADMIN.CREATE_USER,
    PERMISSIONS.ADMIN.READ_USER,
    PERMISSIONS.ADMIN.UPDATE_USER,
    PERMISSIONS.ADMIN.DELETE_USER,

    // language management
    PERMISSIONS.COMMON.READ_LANGUAGE,
    PERMISSIONS.COMMON.CREATE_LANGUAGE,
    PERMISSIONS.COMMON.UPDATE_LANGUAGE,
    PERMISSIONS.COMMON.DELETE_LANGUAGE,
];
