---
galaxy_info:
  author: Softeko
  description: System timezone, essential packages, and automatic security updates
  company: Softeko
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - system
    - packages
    - security
