---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Create test admin user
      ansible.builtin.user:
        name: testadmin
        state: present
    - name: Install Docker (prerequisite)
      ansible.builtin.apt:
        name:
          - docker.io
          - python3-docker
        state: present
        update_cache: true
    - name: Start Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
  roles:
    - role: deploy-postgres
