---
galaxy_info:
  author: Softeko
  description: Install and configure Docker CE with log rotation
  company: Softeko
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - docker
    - container
    - infrastructure
