import type { Metadata } from 'next';
import { Bricolage_Grotesque, Inter } from 'next/font/google';
import './globals.css';

import PublicNavbar from '@/components/PublicNavbar';
import AuthCheck from '@modules/auth/components/AuthCheck';
import ReduxProvider from '@/providers/redux';
import { Toaster } from 'sonner';
import { AuthProvider } from '@/context/auth-context';
import ObservabilityProvider from '@/components/ObservabilityProvider';
import { ThemeProvider } from '@repo/ui/components/common/ThemeProvider';

const bricolage = Bricolage_Grotesque({
  variable: '--font-bricolage',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body
        className={`${bricolage.variable} ${inter.variable} flex w-full flex-col items-center antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <ObservabilityProvider />
          <ReduxProvider>
            <AuthProvider>
              <PublicNavbar />
              <AuthCheck />
              <main className="w-full max-w-[1920px]">{children}</main>
            </AuthProvider>
          </ReduxProvider>
          <Toaster position="bottom-left" duration={10000} />
        </ThemeProvider>
      </body>
    </html>
  );
}
