type SeedUser = {
  id?: string;
  userName: string;
  email: string;
  password: string;
  providerName: string;
  registeredAt: Date;
  isVerified: boolean;
  roles: string[];
};

export const userData: SeedUser[] = [
  {
    id: "3566748c-6284-4f06-ace0-2200e1864b30",
    userName: "development",
    email: "development@softeko.co",
    password: "admin123",
    providerName: "email",
    registeredAt: new Date(),
    isVerified: true,
    roles: ["admin"], // ADMIN role by name
  },
];

export const languageData: { name: string }[] = [
  { name: "Afrikaans" },
  { name: "Albanian - shqip" },
  { name: "Amharic - አማርኛ" },
  { name: "Arabic - العربية" },
  { name: "Aragonese - aragonés" },
  { name: "Armenian - հայերեն" },
  { name: "Asturian - asturianu" },
  { name: "Azerbaijani - azərbaycan dili" },
  { name: "Basque - euskara" },
  { name: "Belarusian - беларуская" },
  { name: "Bengali - বাংলা" },
  { name: "Bosnian - bosanski" },
  { name: "Breton - brezhoneg" },
  { name: "Bulgarian - български" },
  { name: "Catalan - català" },
  { name: "Central Kurdish - کوردیی ناوەندی" },
  { name: "Chinese - 中文" },
  { name: "Chinese (Hong Kong) - 中文（香港）" },
  { name: "Chinese (Simplified) - 中文（简体）" },
  { name: "Chinese (Traditional) - 中文（繁體）" },
  { name: "Corsican" },
  { name: "Croatian - hrvatski" },
  { name: "Czech - čeština" },
  { name: "Danish - dansk" },
  { name: "Dutch - Nederlands" },
  { name: "English" },
  { name: "English (Australia)" },
  { name: "English (Canada)" },
  { name: "English (India)" },
  { name: "English (New Zealand)" },
  { name: "English (South Africa)" },
  { name: "English (United Kingdom)" },
  { name: "English (United States)" },
  { name: "Esperanto - esperanto" },
  { name: "Estonian - eesti" },
  { name: "Faroese - føroyskt" },
  { name: "Filipino" },
  { name: "Finnish - suomi" },
  { name: "French - français" },
  { name: "French (Canada) - français (Canada)" },
  { name: "French (France) - français (France)" },
  { name: "French (Switzerland) - français (Suisse)" },
  { name: "Galician - galego" },
  { name: "Georgian - ქართული" },
  { name: "German - Deutsch" },
  { name: "German (Austria) - Deutsch (Österreich)" },
  { name: "German (Germany) - Deutsch (Deutschland)" },
  { name: "German (Liechtenstein) - Deutsch (Liechtenstein)" },
  { name: "German (Switzerland) - Deutsch (Schweiz)" },
  { name: "Greek - Ελληνικά" },
  { name: "Guarani" },
  { name: "Gujarati - ગુજરાતી" },
  { name: "Hausa" },
  { name: "Hawaiian - ʻōlelo Hawaiʻi" },
  { name: "Hebrew - עברית" },
  { name: "Hindi - हिन्दी" },
  { name: "Hungarian - magyar" },
  { name: "Icelandic - íslenska" },
  { name: "Indonesian - Indonesia" },
  { name: "Interlingua" },
  { name: "Irish - Gaeilge" },
  { name: "Italian - italiano" },
  { name: "Italian (Italy) - italiano (Italia)" },
  { name: "Italian (Switzerland) - italiano (Svizzera)" },
  { name: "Japanese - 日本語" },
  { name: "Kannada - ಕನ್ನಡ" },
  { name: "Kazakh - қазақ" },
  { name: "Khmer - ខ្មែរ" },
  { name: "Korean - 한국어" },
  { name: "Kurdish - Kurdî" },
  { name: "Kyrgyz - кыргыз" },
  { name: "Lao - ລາວ" },
  { name: "Latin" },
  { name: "Latvian - latviešu" },
  { name: "Lingala - lingála" },
  { name: "Lithuanian - lietuvių" },
  { name: "Macedonian - македонски" },
  { name: "Malay - Bahasa Melayu" },
  { name: "Malayalam - മലയാളം" },
  { name: "Maltese - Malti" },
  { name: "Marathi - मराठी" },
  { name: "Mongolian - монгол" },
  { name: "Nepali - नेपाली" },
  { name: "Norwegian - norsk" },
  { name: "Norwegian Bokmål - norsk bokmål" },
  { name: "Norwegian Nynorsk - nynorsk" },
  { name: "Occitan" },
  { name: "Oriya - ଓଡ଼ିଆ" },
  { name: "Oromo - Oromoo" },
  { name: "Pashto - پښتو" },
  { name: "Persian - فارسی" },
  { name: "Polish - polski" },
  { name: "Portuguese - português" },
  { name: "Portuguese (Brazil) - português (Brasil)" },
  { name: "Portuguese (Portugal) - português (Portugal)" },
  { name: "Punjabi - ਪੰਜਾਬੀ" },
  { name: "Romanian - română" },
  { name: "Russian - русский" },
  { name: "Scottish Gaelic" },
  { name: "Serbian - српски" },
  { name: "Serbo - хрватски" },
  { name: "Shona - chiShona" },
  { name: "Sindhi" },
  { name: "Sinhala - සිංහල" },
  { name: "Slovak - slovenčina" },
  { name: "Slovenian - slovenščina" },
  { name: "Somali - Soomaali" },
  { name: "Southern Sotho" },
  { name: "Spanish - español" },
  { name: "Spanish (Argentina) - español (Argentina)" },
  { name: "Spanish (Latin America) - español (Latinoamérica)" },
  { name: "Spanish (Mexico) - español (México)" },
  { name: "Spanish (Spain) - español (España)" },
  { name: "Spanish (United States) - español (Estados Unidos)" },
  { name: "Sundanese - Basa Sunda" },
  { name: "Swahili - Kiswahili" },
  { name: "Swedish - svenska" },
  { name: "Tajik - тоҷикӣ" },
  { name: "Tamil - தமிழ்" },
  { name: "Telugu - తెలుగు" },
  { name: "Thai - ไทย" },
  { name: "Tigrinya - ትግርኛ" },
  { name: "Tongan - lea fakatonga" },
  { name: "Turkish - Türkçe" },
  { name: "Turkmen" },
  { name: "Twi" },
  { name: "Ukrainian - українська" },
  { name: "Urdu - اردو" },
  { name: "Uyghur" },
  { name: "Uzbek - Oʻzbekcha" },
  { name: "Vietnamese - Tiếng Việt" },
  { name: "Walloon - waòlon" },
  { name: "Welsh - Cymraeg" },
  { name: "Western Frisian" },
  { name: "Xhosa" },
  { name: "Yiddish" },
  { name: "Yoruba - èdè Yorùbá" },
  { name: "Zulu - isiZulu" },
];
