import type { Metadata } from 'next';
import { Bricolage_Grotesque, Inter } from 'next/font/google';
import './globals.css';

import { AuthProvider } from '@/context/auth-context';
import QueryProvider from '@/providers/query-provider';
import ReduxProvider from '@/providers/redux-provider';
import { Toaster } from 'sonner';
import { VisitorViewProvider } from '@/context';
import AuthCheck from '@modules/auth/components/shared/AuthCheck';
import ObservabilityProvider from '@/components/ObservabilityProvider';
import BackToTopButton from '@repo/ui/components/common/BackToTopButton';

const bricolage = Bricolage_Grotesque({
  variable: '--font-bricolage',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${bricolage.variable} ${inter.variable} flex w-full flex-col items-center antialiased`}
        suppressHydrationWarning={true}
      >
        <ObservabilityProvider />
        <VisitorViewProvider>
          <QueryProvider>
            <ReduxProvider>
              <AuthProvider>
                <AuthCheck />
                <main className="relative w-full max-w-[1920px]">
                  {children}
                  <BackToTopButton />
                </main>
              </AuthProvider>
            </ReduxProvider>
          </QueryProvider>
        </VisitorViewProvider>
        <Toaster position="bottom-left" duration={10000} />
      </body>
    </html>
  );
}
