import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { AuthProvider } from '@/context/auth-context';
import QueryProvider from '@/providers/query-provider';
import ReduxProvider from '@/providers/redux-provider';
import { Toaster } from 'sonner';
import { VisitorViewProvider } from '@/context';
import AuthCheck from '@modules/auth/components/shared/AuthCheck';
import ObservabilityProvider from '@/components/ObservabilityProvider';
import BackToTopButton from '@repo/ui/components/common/BackToTopButton';
import { ThemeProvider } from '@repo/ui/components/common/ThemeProvider';
import { getPublishedSiteSeoSettings } from '@modules/content/seo/services/seo-service';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export async function generateMetadata(): Promise<Metadata> {
  const settings = await getPublishedSiteSeoSettings();

  if (!settings) {
    return {
      title: 'Create Next App',
      description: 'Generated by create next app',
    };
  }

  const titleTemplate = settings.titleTemplate || '%s';

  let metadataBase: URL | undefined;
  if (settings.canonicalBaseUrl) {
    try {
      metadataBase = new URL(settings.canonicalBaseUrl);
    } catch {
      metadataBase = undefined;
    }
  }

  return {
    title: {
      template: titleTemplate,
      default: titleTemplate.replace('%s', 'Home'),
    },
    description: settings.metaDescription || undefined,
    keywords: settings.metaKeywords || undefined,
    ...(metadataBase ? { metadataBase } : {}),
    icons: settings.faviconUrl ? { icon: settings.faviconUrl } : undefined,
    openGraph: {
      title: settings.ogTitle || undefined,
      description: settings.ogDescription || undefined,
      images: settings.ogImageUrl ? [{ url: settings.ogImageUrl }] : undefined,
      type: (settings.ogType as 'website' | 'article') || 'website',
    },
    twitter: {
      card: (settings.twitterCard as 'summary' | 'summary_large_image') || undefined,
      site: settings.twitterHandle || undefined,
    },
    verification: {
      google: settings.googleSiteVerification || undefined,
      other: settings.bingSiteVerification
        ? { 'msvalidate.01': settings.bingSiteVerification }
        : undefined,
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getPublishedSiteSeoSettings();
  const organizationJsonLd = settings?.organizationJsonLd;

  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body
        className={`${inter.variable} flex w-full flex-col items-center antialiased`}
        suppressHydrationWarning={true}
      >
        {organizationJsonLd && (organizationJsonLd.name || organizationJsonLd.logoUrl) && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                '@context': 'https://schema.org',
                '@type': 'Organization',
                name: organizationJsonLd.name ?? undefined,
                logo: organizationJsonLd.logoUrl ?? undefined,
                sameAs: organizationJsonLd.sameAs?.length ? organizationJsonLd.sameAs : undefined,
              }),
            }}
          />
        )}
        {settings?.googleAnalyticsId && (
          <>
            <script
              async
              src={`https://www.googletagmanager.com/gtag/js?id=${settings.googleAnalyticsId}`}
            />
            <script
              dangerouslySetInnerHTML={{
                __html: `window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', ${JSON.stringify(settings.googleAnalyticsId)});`,
              }}
            />
          </>
        )}
        <ThemeProvider>
          <ObservabilityProvider />
          <VisitorViewProvider>
            <QueryProvider>
              <ReduxProvider>
                <AuthProvider>
                  <AuthCheck />
                  <main className="relative w-full max-w-[1920px]">
                    {children}
                    <BackToTopButton />
                  </main>
                </AuthProvider>
              </ReduxProvider>
            </QueryProvider>
          </VisitorViewProvider>
          <Toaster position="bottom-left" duration={10000} />
        </ThemeProvider>
      </body>
    </html>
  );
}
